### PR TITLE
Fix message type

### LINKED ISSUE #44: `BerichtSoort` isn't always `Bericht`
It can also be `Mededeling` now it throws a `FileNotFoundException` if it is a mededeling
https://github.com/iLexiconn/Magister.java/blob/master/src/main/java/net/ilexiconn/magister/handler/MessageHandler.java#L113

### PR DESCRIPTION
**Pull request by KeizerDev**
Should close #44

### CODE REVIEW

**Comment by iLexiconn** [comment]
Can you make it an enum please? :)

**Comment by KeizerDev** [comment]
Yeah sure :+1:

**Comment by KeizerDev** [comment]
Can you add it, I don't know where I have to return the string and I'm not that familiar with an enum casting an Integer.

**Comment by iLexiconn** [comment]
:+1:

**Pull request merged**
