### PR TITLE
Added User object to get rid of the hashmap.put methods

### PR DESCRIPTION
**Pull request by KeizerDev**

### CODE REVIEW

**Comment by iLexiconn** [comment]
Please fix the variable names first

**Comment by KeizerDev** [comment]
@iLexiconn Yeah, sorry :wink:

**Comment by KeizerDev** [comment]
Just copy and pasted it from another project.

**Comment by KeizerDev** [comment]
Btw, i'll change it to a serialized object.

**Comment by KeizerDev** [comment]
You can revert it.

**Comment by iLexiconn** [comment]
Too late. :/

**Comment by KeizerDev** [comment]
There is the `Revert` button for :p

**Comment by iLexiconn** [comment]
I know, but I already made changes to the class.

**Comment by KeizerDev** [comment]
Already fixed it tho

**Comment by iLexiconn** [comment]
Make a new pr for it. :p

**Comment by KeizerDev** [comment]
Lol, you did it already ;p. 

Btw.
Why do you keep the getters for `password`, `username` and `stayLoggedIn`?  
`user.password`, etc. will actually do the same.

**Comment by iLexiconn** [comment]
Because they're private, and I want other classes to be able to access them.

**Comment by iLexiconn** [comment]
Well, maybe we shouldn't save the password as a variable at all.

**Comment by KeizerDev** [comment]
Just do it. I want it :D

**Comment by iLexiconn** [comment]
Why do you need it?

**Comment by KeizerDev** [comment]
Testing purposes

**Comment by KeizerDev** [comment]
Lol, joking. You can make a test if people are not changing their password in their current password for example.

**Comment by iLexiconn** [comment]
Pretty sure magister returns an error if that's the case.

**Comment by KeizerDev** [comment]
True, but data is data and as a library for mainly devices you should try to minimize it as most as possible.

**Comment by KeizerDev** [comment]
And what if people are losing their session? Do you want them to relog or just get the one you can store? I'm pretty sure every Android app that is build for Magister stores that kind of stuff

**Comment by iLexiconn** [comment]
I really hope you aren't getting all those passwords from your Mister app.

**Comment by KeizerDev** [comment]
Not anymore. Got like 70 with it just to keep on with development when I left school.

**Comment by KeizerDev** [comment]
The rest of the list was from other sources

**Comment by KeizerDev** [comment]
But that's not my point.

**Comment by iLexiconn** [comment]
I really don't think this is acceptable. I'm not going to story the password in any kind of way.

**Comment by KeizerDev** [comment]
Lol, I hope you know that you firstly won't store them and secondly, there are like 1000 ways to still get them. But yeah, it is your library so you can choose

**Comment by KeizerDev** [comment]
And what I mean with store is locally.

**Pull request merged**
